#pragma once
#define GRYPHN_INCLUDE
#include <platform/gryphn_platform_include.h>
#include <core/instance/init/gryphn_init.h>
#include <core/instance/gryphn_instance.h>
#include <core/debugger/gryphn_debugger.h>
#include <core/output_device/gryphn_physical_output_device.h>
#include <core/window_surface/gryphn_surface.h>
#include <core/window_surface/gryphn_surface_create_functions.h>
#include <core/presentation_queue/gryphn_presentation_queue.h>
#include <core/shader_module/gryphn_shader_module.h>
#include <core/pipelines/graphics_pipeline/gryphn_graphics_pipeline.h>
