#pragma once

typedef enum gnReturnCode {

    GN_SUCCESS = 0,

    // non spec return codes
    GN_FAILED_CREATE_OBJECT, GN_FAILED_TO_ALLOCATE_OBJECT,
    GN_FAILED_TO_ALLOCATE_MEMORY, GN_OUT_OUT_HOST_MEMEORY,
    GN_OUT_OUT_DEVICE_MEMORY,


    GN_UNLOADED_EXTENSION = -1,
    GN_UNLOADED_LAYER = -2,
    GN_UNSUPPORTED_API = -3,
    GN_UNKNOWN_ERROR = -4



    // GN_SUCCESS,
    // GN_UNKNOWN_RENDERINGAPI,
    // GN_UNSUPPORTED_RENDERING_API,
    // GN_UNSUPPORTED_IMAGE_FORMAT,
    // GN_UNABLE_TO_LOAD_DYNAMIC_LIBARRY,
    // GN_FAILED_CREATE_INSTANCE,
    // GN_FAILED_TO_CREATE_DEBUGGER,
    // GN_FAILED_TO_CREATE_DEVICE,
    // GN_FAILED_TO_ATTACH_WINDOW,
    // GN_INVALID_INSTANCE,
    // GN_DEBUGGER_EXISTS,
    // GN_NO_SUPPORTED_FORMATS,
    // GN_NO_SUPPORTED_PRESENT_MODES,
    // GN_UNKNOWN_IMAGE_FORMAT,
    // GN_FAILED_TO_CREATE_PRESENTATION_QUEUE,
    // GN_WINDOW_IN_USE,
    // GN_UNSUPPORTED_IMAGE_COUNT,
    // GN_FAILED_TO_CREATE_IMAGE_VIEW,
    // GN_FAILED_TO_CREATE_SHADER_MODULE,
    // GN_FAILED_TO_CONVERT_SHADER_CODE,
    // GN_FAILED_TO_FIND_ENTRY_POINT,
    // GN_FAILED_TO_CREATE_UNIFORM_LAYOUT,
    // GN_FAILED_TO_CREATE_RENDER_PASS,
    // GN_FAILED_TO_CREATE_GRAPHICS_PIPELINE,
    // GN_UNSUPPORTED_SHADER_MODULE,
    // GN_UNKNOWN_SUBPASS,
    // GN_FAILED_TO_CREATE_FRAMEBUFFER,
    // GN_DIVERGENT_RENDERPASS,
    // GN_FAILED_TO_CREATE_COMMAND_POOL,
    // GN_FAILED_TO_BEGIN_RECORDING,
    // GN_FAIELD_TO_END_RECORDING,
    // GN_FAILED_TO_ALLOCATE_COMMAND_BUFFERS,
    // GN_FAILED_TO_CREATE_FENCE,
    // GN_FAILED_TO_CREATE_SEMAPHORE,
    // GN_FAILED_TO_SUBMIT_COMMAND_BUFFER,
    // GN_OUT_OF_DATE_PRESENTATION_QUEUE,
    // GN_SUBOPTIMAL_PRESENTATION_QUEUE,
    // GN_FAILED_TO_CREATE_BUFFER,
    // GN_FAILED_TO_ALLOCATE_MEMORY,
    // GN_FAILED_TO_CREATE_IMAGE,
    // GN_FAILED_TO_CREATE_SAMPLER,
    // GN_FAILED_TO_LOAD_FUNCTION,
    // GN_FAILED_TO_INIT_OPENGL
} gnReturnCode;
