#pragma once

typedef enum gnReturnCode_t {
    GN_SUCCESS,
    GN_UNKNOWN_RENDERINGAPI,
    GN_UNSUPPORTED_RENDERING_API,
    GN_UNABLE_TO_LOAD_DYNAMIC_LIBARRY

    // GN_UNKNOWN_ERROR,
    // GN_UNKNOWN_FRAMEBUFFER_ATTACHMENT,
    // GN_UNKNOWN_SHADER_MODULE,
    // GN_UNKNOWN_FUNCTION,
    // GN_SHADER_FAILED_TO_COMPILE,
    // GN_UNSUPPORTED_COLOR_FORMAT,
    // GN_UNKNOWN_COLOR_FORMAT,
    // GN_FUNCTION_NOT_FOUND,
    // GN_FAILED_CREATE_DEVICE,
    // GN_FAILED_CREATE_GRAPHICS_PIPELINE,
    // GN_FAILED_CREATE_PRESENTATION_QUEUE,
    // GN_FAILED_TO_CREATE_FRAMEBUFFER,
    // GN_FAILED_CREATE_RENDERPASS,
    // GN_FAILED_CREATE_INSTANCE,
    // GN_FAILED_TO_ATTACH_WINDOW,
    // GN_FAILED_TO_CREATE_IMAGE
} gnReturnCode;

typedef gnReturnCode gnErrorCode;
